name: Build macOS

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-13
    steps:
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Force Xcode 15.4
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: brew install pkg-config gtk4 || echo "This step 'fails' every time but it's just a brew linking error - not important."
    - name: Patch libffi
      run: sed -i '' 's/-I..includedir.//g' /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/13/libffi.pc
    - name: Build
      run: |
        swift build --target GtkCodeGen && \
        cd Examples && \
        swift build --target SwiftCrossUI && \
        swift build --target GtkBackend && \
        swift build --target CounterExample && \
        swift build --target ControlsExample && \
        swift build --target RandomNumberGeneratorExample && \
        swift build --target WindowingExample && \
        swift build --target GreetingGeneratorExample && \
        swift build --target NavigationExample && \
        swift build --target SplitExample && \
        swift build --target GtkExample
    - name: Test
      run: swift test
