name: Build Linux

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt update && \
        sudo apt install -y libgtk-4-dev libgtk-3-dev clang
    - name: Build
      run: |
        cd Examples && \
        swift build --target GtkCodeGen && \
        swift build --target SwiftCrossUI && \
        swift build --target GtkBackend && \
        swift build --target Gtk3Backend && \
        swift build --target CounterExample && \
        swift build --target ControlsExample && \
        swift build --target RandomNumberGeneratorExample && \
        swift build --target WindowingExample && \
        swift build --target GreetingGeneratorExample && \
        swift build --target NavigationExample && \
        swift build --target SplitExample && \
        swift build --target StressTestExample && \
        swift build --target SpreadsheetExample && \
        swift build --target NotesExample && \
        swift build --target GtkExample
    # - name: Test
    #   run: swift test
